# Generated by Django 4.2.2 on 2023-07-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_app', '0002_alter_captionimage_caption_background_color1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionimage',
            name='caption_color1',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='captionimage',
            name='caption_color2',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='captionimage',
            name='caption_color3',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
